apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-container
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: reactive-container2
  template:
    metadata:
      labels:
        app: reactive-container2
    spec:
      containers:
      - name: reactive
        image: francomatheus/reactive-mvc:1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "400Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            # httpHeaders:
            # - name: Custom-Header
            #   value: Awesome
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 20
          periodSeconds: 3