apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
  namespace: metrics  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
