apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "ghost"
        track: "canary"
    spec:
      containers:
        - name: "nginx"
      image: "nginx:1.9.12"
      ports:
        - containerPort: 80
      lifecycle:
        preStop:
          exec:
            command: ["/usr/sbin/nginx","-s","quit"]
      livenessProbe:
        httpGet:
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 30
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 5
        timeoutSeconds: 1
      volumeMounts:
        - name: "nginx-conf"
          mountPath: "/etc/nginx/conf.d"